const data = [
  {
    title: 'Brown eggs',
    category: 'dairy',
    description: 'Raw organic brown eggs in a basket',
    images: ['0.jpg'],
    imgHeight: 600,
    imgWidth: 400,
    price: 28.1,
    rating: 4,
  },
  {
    title: 'Sweet fresh stawberry',
    category: 'fruit',
    description: 'Sweet fresh stawberry on the wooden table',
    images: ['1.jpg'],
    imgHeight: 450,
    imgWidth: 299,
    price: 29.45,
    rating: 4,
  },
  {
    title: 'Asparagus',
    category: 'vegetable',
    description: 'Asparagus with ham on the wooden table',
    images: ['2.jpg'],
    imgHeight: 450,
    imgWidth: 299,
    price: 18.95,
    rating: 3,
  },
  {
    title: 'Green smoothie',
    category: 'dairy',
    description:
      "Glass of green smoothie with quail egg's yolk, served with cocktail tube, green apple and baby spinach leaves over tin surface.",
    images: ['3.jpg'],
    imgHeight: 600,
    imgWidth: 399,
    price: 17.68,
    rating: 4,
  },
  {
    title: 'Raw legums',
    category: 'vegetable',
    description: 'Raw legums on the wooden table',
    images: ['4.jpg'],
    imgHeight: 450,
    imgWidth: 299,
    price: 17.11,
    rating: 2,
  },
  {
    title: 'Baking cake',
    category: 'dairy',
    description:
      'Baking cake in rural kitchen - dough  recipe ingredients (eggs, flour, sugar) on vintage wooden table from above.',
    images: ['5.jpg'],
    imgHeight: 450,
    imgWidth: 675,
    price: 11.14,
    rating: 4,
  },
  {
    title: 'Pesto with basil',
    category: 'vegetable',
    description: 'Italian traditional pesto with basil, chesse and oil',
    images: ['6.jpg'],
    imgHeight: 450,
    imgWidth: 299,
    price: 18.19,
    rating: 2,
  },
  {
    title: 'Hazelnut in black ceramic bowl',
    category: 'vegetable',
    description:
      'Hazelnut in black ceramic bowl on old wooden background. forest wealth. rustic style. selective focus',
    images: ['7.jpg'],
    imgHeight: 450,
    imgWidth: 301,
    price: 27.35,
    rating: 0,
  },
  {
    title: 'Fresh stawberry',
    category: 'fruit',
    description: 'Sweet fresh stawberry on the wooden table',
    images: ['8.jpg'],
    imgHeight: 600,
    imgWidth: 399,
    price: 28.59,
    rating: 4,
  },
  {
    title: 'Lemon and salt',
    category: 'fruit',
    description: 'Rosemary, lemon and salt on the table',
    images: ['9.jpg'],
    imgHeight: 450,
    imgWidth: 299,
    price: 15.79,
    rating: 5,
  },
  {
    title: 'Homemade bread',
    category: 'bakery',
    description: 'Homemade bread',
    images: ['10.jpg'],
    imgHeight: 450,
    imgWidth: 301,
    price: 17.48,
    rating: 3,
  },
  {
    title: 'Legums',
    category: 'vegetable',
    description: 'Cooked legums on the wooden table',
    images: ['11.jpg'],
    imgHeight: 600,
    imgWidth: 399,
    price: 14.77,
    rating: 0,
  },
  {
    title: 'Fresh tomato',
    category: 'vegetable',
    description: 'Fresh tomato juice with basil',
    images: ['12.jpg'],
    imgHeight: 600,
    imgWidth: 903,
    price: 16.3,
    rating: 2,
  },
  {
    title: 'Healthy breakfast',
    category: 'fruit',
    description:
      'Healthy breakfast set. rice cereal or porridge with berries and honey over rustic wood background',
    images: ['13.jpg'],
    imgHeight: 450,
    imgWidth: 350,
    price: 13.02,
    rating: 2,
  },
  {
    title: 'Green beans',
    category: 'vegetable',
    description: 'Raw organic green beans ready to eat',
    images: ['14.jpg'],
    imgHeight: 450,
    imgWidth: 300,
    price: 28.79,
    rating: 1,
  },
  {
    title: 'Baked stuffed portabello mushrooms',
    category: 'bakery',
    description:
      'Homemade baked stuffed portabello mushrooms with spinach and cheese',
    images: ['15.jpg'],
    imgHeight: 600,
    imgWidth: 400,
    price: 20.31,
    rating: 1,
  },
  {
    title: 'Strawberry jelly',
    category: 'fruit',
    description: 'Homemade organic strawberry jelly in a jar',
    images: ['16.jpg'],
    imgHeight: 400,
    imgWidth: 600,
    price: 14.18,
    rating: 1,
  },
  {
    title: 'Pears juice',
    category: 'fruit',
    description: 'Fresh pears juice on the wooden table',
    images: ['17.jpg'],
    imgHeight: 600,
    imgWidth: 398,
    price: 19.49,
    rating: 4,
  },
  {
    title: 'Fresh pears',
    category: 'fruit',
    description: 'Sweet fresh pears on the wooden table',
    images: ['18.jpg'],
    imgHeight: 600,
    imgWidth: 398,
    price: 15.12,
    rating: 5,
  },
  {
    title: 'Caprese salad',
    category: 'vegetable',
    description:
      'Homemade healthy caprese salad with tomato mozzarella and basil',
    images: ['19.jpg'],
    imgHeight: 400,
    imgWidth: 600,
    price: 16.76,
    rating: 5,
  },
  {
    title: 'Oranges',
    category: 'fruit',
    description:
      'Orange popsicle ice cream bars made from fresh oranges.  a refreshing summer treat.',
    images: ['20.jpg'],
    imgHeight: 450,
    imgWidth: 274,
    price: 21.48,
    rating: 4,
  },
  {
    title: 'Vegan food',
    category: 'vegetable',
    description: 'Concept of vegan food',
    images: ['21.jpg'],
    imgHeight: 450,
    imgWidth: 299,
    price: 29.66,
    rating: 4,
  },
  {
    title: 'Breakfast with muesli',
    category: 'dairy',
    description: 'Concept of healthy breakfast with muesli',
    images: ['22.jpg'],
    imgHeight: 450,
    imgWidth: 299,
    price: 22.7,
    rating: 2,
  },
  {
    title: 'Honey',
    category: 'bakery',
    description: 'Honey and honeycell on the table',
    images: ['23.jpg'],
    imgHeight: 450,
    imgWidth: 299,
    price: 17.01,
    rating: 2,
  },
  {
    title: 'Breakfast with cottage',
    category: 'fruit',
    description: 'Healthy breakfast with cottage cheese and strawberry',
    images: ['24.jpg'],
    imgHeight: 600,
    imgWidth: 398,
    price: 14.05,
    rating: 1,
  },
  {
    title: 'Strawberry smoothie',
    category: 'fruit',
    description:
      'Glass of red strawberry smoothie with chia seeds, served with retro cocktail tube, fresh mint and strawberries over dark background',
    images: ['25.jpg'],
    imgHeight: 600,
    imgWidth: 400,
    price: 28.86,
    rating: 2,
  },
  {
    title: 'Strawberry and mint',
    category: 'fruit',
    description: 'Homemade muesli with strawberry and mint',
    images: ['26.jpg'],
    imgHeight: 450,
    imgWidth: 299,
    price: 26.21,
    rating: 4,
  },
  {
    title: 'Ricotta',
    category: 'dairy',
    description: 'Ricotta with berry and mint',
    images: ['27.jpg'],
    imgHeight: 600,
    imgWidth: 398,
    price: 27.81,
    rating: 5,
  },
  {
    title: 'Cuban sandwiche',
    category: 'bakery',
    description:
      'Homemade traditional cuban sandwiches with ham pork and cheese',
    images: ['28.jpg'],
    imgHeight: 450,
    imgWidth: 300,
    price: 18.5,
    rating: 4,
  },
  {
    title: 'Granola',
    category: 'dairy',
    description:
      'Glass jar with homemade granola and yogurt with nuts, raspberries and blackberries on wooden cutting board over white textile in day light',
    images: ['29.jpg'],
    imgHeight: 450,
    imgWidth: 300,
    price: 29.97,
    rating: 3,
  },
  {
    title: 'Smoothie with chia seeds',
    category: 'fruit',
    description:
      'Glass of red strawberry smoothie with chia seeds, served with retro cocktail tube, fresh mint and strawberries over wooden table',
    images: ['30.jpg'],
    imgHeight: 600,
    imgWidth: 900,
    price: 25.26,
    rating: 5,
  },
  {
    title: 'Yogurt',
    category: 'dairy',
    description: 'Homemade yogurt with raspberry and mint',
    images: ['31.jpg'],
    imgHeight: 450,
    imgWidth: 299,
    price: 27.61,
    rating: 4,
  },
  {
    title: 'Sandwich with salad',
    category: 'vegetable',
    description: 'Vegan sandwich with salad, tomato and radish',
    images: ['32.jpg'],
    imgHeight: 600,
    imgWidth: 398,
    price: 22.48,
    rating: 5,
  },
  {
    title: 'Cherry',
    category: 'fruit',
    description: 'Cherry with sugar on old table',
    images: ['33.jpg'],
    imgHeight: 600,
    imgWidth: 400,
    price: 14.35,
    rating: 5,
  },
  {
    title: 'Raw asparagus',
    category: 'vegetable',
    description: 'Raw fresh asparagus salad with cheese and dressing',
    images: ['34.jpg'],
    imgHeight: 600,
    imgWidth: 400,
    price: 22.97,
    rating: 4,
  },
  {
    title: 'Corn',
    category: 'vegetable',
    description: 'Grilled corn on the cob with salt and butter',
    images: ['35.jpg'],
    imgHeight: 450,
    imgWidth: 300,
    price: 13.55,
    rating: 2,
  },
  {
    title: 'Vegan',
    category: 'vegan',
    description: 'Concept of healthy vegan eating',
    images: ['36.jpg'],
    imgHeight: 600,
    imgWidth: 398,
    price: 28.96,
    rating: 5,
  },
  {
    title: 'Fresh blueberries',
    category: 'fruit',
    description:
      'Healthy breakfast. berry crumble with fresh blueberries, raspberries, strawberries, almond, walnuts, pecans, yogurt, and mint in ceramic plates over white wooden surface, top view',
    images: ['37.jpg'],
    imgHeight: 450,
    imgWidth: 321,
    price: 21.01,
    rating: 4,
  },
  {
    title: 'Smashed avocado',
    category: 'fruit',
    description:
      'Vegan sandwiches with smashed avocado, tomatoes and radish. top view',
    images: ['38.jpg'],
    imgHeight: 450,
    imgWidth: 450,
    price: 25.88,
    rating: 0,
  },
  {
    title: 'Italian ciabatta',
    category: 'bakery',
    description:
      'Italian ciabatta bread cut in slices on wooden chopping board with herbs, garlic and olives over dark grunge backdrop, top view',
    images: ['39.jpg'],
    imgHeight: 450,
    imgWidth: 565,
    price: 15.18,
    rating: 1,
  },
  {
    title: 'Rustic breakfast',
    category: 'dairy',
    description:
      'Rustic healthy breakfast set. cooked buckwheat groats with milk and honey on dark grunge backdrop. top view, copy space',
    images: ['40.jpg'],
    imgHeight: 450,
    imgWidth: 307,
    price: 21.32,
    rating: 0,
  },
  {
    title: 'Sliced lemons',
    category: 'fruit',
    description:
      'Heap of whole and sliced lemons and limes with mint in vintage metal grid box over old wooden table with turquoise wooden background. dark rustic style.',
    images: ['41.jpg'],
    imgHeight: 600,
    imgWidth: 900,
    price: 27.14,
    rating: 2,
  },
  {
    title: 'Plums',
    category: 'fruit',
    description: 'Yellow and red sweet plums',
    images: ['42.jpg'],
    imgHeight: 450,
    imgWidth: 299,
    price: 19.18,
    rating: 1,
  },
  {
    title: 'French fries',
    category: 'bakery',
    description: 'Homemade oven baked french fries with ketchup',
    images: ['43.jpg'],
    imgHeight: 600,
    imgWidth: 400,
    price: 18.32,
    rating: 3,
  },
  {
    title: 'Strawberries',
    category: 'fruit',
    description:
      'Healthy breakfast set. rice cereal or porridge with fresh strawberry, apricots, almond and honey over white rustic wood backdrop, top view, \u0000',
    images: ['44.jpg'],
    imgHeight: 450,
    imgWidth: 352,
    price: 15.13,
    rating: 3,
  },
  {
    title: 'Ground beef meat burger',
    category: 'meat',
    description:
      'Raw ground beef meat burger steak cutlets with seasoning on vintage wooden boards, black background',
    images: ['45.jpg'],
    imgHeight: 450,
    imgWidth: 675,
    price: 11.73,
    rating: 5,
  },
  {
    title: 'Tomatoes',
    category: 'fruit',
    description: 'Organic tomatoes made with love',
    images: ['46.jpg'],
    imgHeight: 450,
    imgWidth: 675,
    price: 26.03,
    rating: 4,
  },
  {
    title: 'Basil',
    category: 'vegetable',
    description: 'Concept of vegan food with basil',
    images: ['47.jpg'],
    imgHeight: 450,
    imgWidth: 678,
    price: 15.19,
    rating: 4,
  },
  {
    title: 'Fruits bouquet',
    category: 'fruit',
    description: 'Abstract citrus fruits bouquet on blue background',
    images: ['48.jpg'],
    imgHeight: 600,
    imgWidth: 401,
    price: 18.18,
    rating: 1,
  },
  {
    title: 'Peaches on branch',
    category: 'fruit',
    description:
      'Peaches on branch with leaves and glasses with peach juice and limonade with ice cubes in aluminum tray over old metal table. dark rustic style. top view.',
    images: ['49.jpg'],
    imgHeight: 600,
    imgWidth: 400,
    price: 25.62,
    rating: 3,
  },
];

export default data;
